
# docker build -t mgrast/shock -f Dockerfile_new .
# docker run --rm --name test -ti mgrast/shock /bin/ash

FROM golang:1.8-alpine


ENV DIR=/go/src/github.com/MG-RAST/Shock

WORKDIR /go/bin

COPY . /go/src/github.com/MG-RAST/Shock

RUN mkdir -p /var/log/shock /usr/local/shock

# set version
RUN cd ${DIR} && \
  VERSION=$(cat VERSION) && \
  sed -i "s/\[% VERSION %\]/${VERSION}/" ${DIR}/shock-server/main.go 


RUN CGO_ENABLED=0 go install -a -installsuffix cgo -v ...

CMD ["/go/bin/shock-server"]