package errors_test

import (
	"testing"

	"github.com/MG-RAST/Shock/shock-server/errors"
	"github.com/stretchr/testify/assert"
)

// TestErrorConstants tests that all error constants are defined
func TestErrorConstants(t *testing.T) {
	// Test that all error constants are non-empty
	assert.NotEmpty(t, errors.MongoDocNotFound, "MongoDocNotFound should not be empty")
	assert.NotEmpty(t, errors.InvalidAuth, "InvalidAuth should not be empty")
	assert.NotEmpty(t, errors.InvalidIndex, "InvalidIndex should not be empty")
	assert.NotEmpty(t, errors.InvalidFileTypeForFilter, "InvalidFileTypeForFilter should not be empty")
	assert.NotEmpty(t, errors.InvalidIndexType, "InvalidIndexType should not be empty")
	assert.NotEmpty(t, errors.NodeReferenced, "NodeReferenced should not be empty")
	assert.NotEmpty(t, errors.IndexExists, "IndexExists should not be empty")
	assert.NotEmpty(t, errors.IndexNotFound, "IndexNotFound should not be empty")
	assert.NotEmpty(t, errors.IndexCreationFailed, "IndexCreationFailed should not be empty")
	assert.NotEmpty(t, errors.InvalidIndexRange, "InvalidIndexRange should not be empty")
	assert.NotEmpty(t, errors.IndexOutBounds, "IndexOutBounds should not be empty")
	assert.NotEmpty(t, errors.NodeExists, "NodeExists should not be empty")
	assert.NotEmpty(t, errors.NodeNotFound, "NodeNotFound should not be empty")
	assert.NotEmpty(t, errors.NodeNoFile, "NodeNoFile should not be empty")
	assert.NotEmpty(t, errors.NodeFileLocked, "NodeFileLocked should not be empty")
	assert.NotEmpty(t, errors.NodeIndexLocked, "NodeIndexLocked should not be empty")
	assert.NotEmpty(t, errors.NodeCreateLockFailed, "NodeCreateLockFailed should not be empty")
	assert.NotEmpty(t, errors.NodeCreateUploadFailed, "NodeCreateUploadFailed should not be empty")
	assert.NotEmpty(t, errors.NodeUpdateLockFailed, "NodeUpdateLockFailed should not be empty")
	assert.NotEmpty(t, errors.NodeUpdateDeleteFailed, "NodeUpdateDeleteFailed should not be empty")
	assert.NotEmpty(t, errors.NodeUpdateAttributeFailed, "NodeUpdateAttributeFailed should not be empty")
	assert.NotEmpty(t, errors.NodeUpdateFormFileFailed, "NodeUpdateFormFileFailed should not be empty")
	assert.NotEmpty(t, errors.NodeUpdateCopyFileFailed, "NodeUpdateCopyFileFailed should not be empty")
	assert.NotEmpty(t, errors.NodeUpdateParseFailed, "NodeUpdateParseFailed should not be empty")
	assert.NotEmpty(t, errors.NodeUpdatePathFailed, "NodeUpdatePathFailed should not be empty")
	assert.NotEmpty(t, errors.NodeUpdateSubsetFailed, "NodeUpdateSubsetFailed should not be empty")
	assert.NotEmpty(t, errors.NodeUpdateFileFailed, "NodeUpdateFileFailed should not be empty")
	assert.NotEmpty(t, errors.NodeUpdateIndexFailed, "NodeUpdateIndexFailed should not be empty")
	assert.NotEmpty(t, errors.NodeUpdateLinkageFailed, "NodeUpdateLinkageFailed should not be empty")
	assert.NotEmpty(t, errors.NodeUpdatePublishFailed, "NodeUpdatePublishFailed should not be empty")
	assert.NotEmpty(t, errors.NodeUpdateUnpublishFailed, "NodeUpdateUnpublishFailed should not be empty")
	assert.NotEmpty(t, errors.NodeUpdateAclFailed, "NodeUpdateAclFailed should not be empty")
	assert.NotEmpty(t, errors.NodeDeleteLockFailed, "NodeDeleteLockFailed should not be empty")
	assert.NotEmpty(t, errors.NodeDeleteFailed, "NodeDeleteFailed should not be empty")
	assert.NotEmpty(t, errors.NodeDatabaseError, "NodeDatabaseError should not be empty")
	assert.NotEmpty(t, errors.NodeStageFailed, "NodeStageFailed should not be empty")
	assert.NotEmpty(t, errors.NoAuth, "NoAuth should not be empty")
	assert.NotEmpty(t, errors.NoEligibleTokens, "NoEligibleTokens should not be empty")
	assert.NotEmpty(t, errors.UnAuth, "UnAuth should not be empty")
	assert.NotEmpty(t, errors.InvalidToken, "InvalidToken should not be empty")
	assert.NotEmpty(t, errors.InvalidFileTypeForNewIndex, "InvalidFileTypeForNewIndex should not be empty")
	assert.NotEmpty(t, errors.InvalidFileTypeForNewCopy, "InvalidFileTypeForNewCopy should not be empty")
	assert.NotEmpty(t, errors.InvalidFileTypeForFilter, "InvalidFileTypeForFilter should not be empty")
	assert.NotEmpty(t, errors.ExpiredUpload, "ExpiredUpload should not be empty")
	assert.NotEmpty(t, errors.InvalidPartNumber, "InvalidPartNumber should not be empty")
	assert.NotEmpty(t, errors.InvalidPartSize, "InvalidPartSize should not be empty")
	assert.NotEmpty(t, errors.InvalidUpload, "InvalidUpload should not be empty")
	assert.NotEmpty(t, errors.PartNumberTooHigh, "PartNumberTooHigh should not be empty")
	assert.NotEmpty(t, errors.TotalPartsExceeded, "TotalPartsExceeded should not be empty")
	assert.NotEmpty(t, errors.ProxyRequest, "ProxyRequest should not be empty")
	assert.NotEmpty(t, errors.ProxyRequestFailed, "ProxyRequestFailed should not be empty")
	assert.NotEmpty(t, errors.ProxyMisconfigured, "ProxyMisconfigured should not be empty")
	assert.NotEmpty(t, errors.ProxyNotFound, "ProxyNotFound should not be empty")
	assert.NotEmpty(t, errors.ProxyForward, "ProxyForward should not be empty")
	assert.NotEmpty(t, errors.InvalidAuthHeader, "InvalidAuthHeader should not be empty")
	assert.NotEmpty(t, errors.InvalidConfig, "InvalidConfig should not be empty")
	assert.NotEmpty(t, errors.InvalidFileSize, "InvalidFileSize should not be empty")
	assert.NotEmpty(t, errors.InvalidIndexForFilter, "InvalidIndexForFilter should not be empty")
	assert.NotEmpty(t, errors.InvalidIndexNoAvail, "InvalidIndexNoAvail should not be empty")
	assert.NotEmpty(t, errors.InvalidNodeData, "InvalidNodeData should not be empty")
	assert.NotEmpty(t, errors.InvalidNodeId, "InvalidNodeId should not be empty")
	assert.NotEmpty(t, errors.InvalidPart, "InvalidPart should not be empty")
	assert.NotEmpty(t, errors.InvalidUrlPassed, "InvalidUrlPassed should not be empty")
	assert.NotEmpty(t, errors.MissingExpiration, "MissingExpiration should not be empty")
	assert.NotEmpty(t, errors.MissingInit, "MissingInit should not be empty")
	assert.NotEmpty(t, errors.NoFileFound, "NoFileFound should not be empty")
	assert.NotEmpty(t, errors.NoUserNoLogin, "NoUserNoLogin should not be empty")
	assert.NotEmpty(t, errors.NoUserNoEmail, "NoUserNoEmail should not be empty")
	assert.NotEmpty(t, errors.NoUserExists, "NoUserExists should not be empty")
	assert.NotEmpty(t, errors.NoUserDeletedUser, "NoUserDeletedUser should not be empty")
	assert.NotEmpty(t, errors.NoUserNoName, "NoUserNoName should not be empty")
	assert.NotEmpty(t, errors.NoUserNoPasswd, "NoUserNoPasswd should not be empty")
	assert.NotEmpty(t, errors.NoUserPasswdMismatch, "NoUserPasswdMismatch should not be empty")
	assert.NotEmpty(t, errors.NoUserUpdateFailure, "NoUserUpdateFailure should not be empty")
	assert.NotEmpty(t, errors.NoUserCreateFailure, "NoUserCreateFailure should not be empty")
	assert.NotEmpty(t, errors.NoUserDeleteFailure, "NoUserDeleteFailure should not be empty")
	assert.NotEmpty(t, errors.NoUserNoId, "NoUserNoId should not be empty")
	assert.NotEmpty(t, errors.NoUserUnAuth, "NoUserUnAuth should not be empty")
	assert.NotEmpty(t, errors.NoTokenProvidedNoLogin, "NoTokenProvidedNoLogin should not be empty")
	assert.NotEmpty(t, errors.TokenExpired, "TokenExpired should not be empty")
	assert.NotEmpty(t, errors.TokenFormatIncorrect, "TokenFormatIncorrect should not be empty")
	assert.NotEmpty(t, errors.UnableToCreateToken, "UnableToCreateToken should not be empty")
	assert.NotEmpty(t, errors.UnableToMakeDirectory, "UnableToMakeDirectory should not be empty")
	assert.NotEmpty(t, errors.UnableToReadFile, "UnableToReadFile should not be empty")
	assert.NotEmpty(t, errors.UnableToSendMail, "UnableToSendMail should not be empty")
	assert.NotEmpty(t, errors.UnableToSetExpiration, "UnableToSetExpiration should not be empty")
	assert.NotEmpty(t, errors.UnableToUnmarshal, "UnableToUnmarshal should not be empty")
	assert.NotEmpty(t, errors.UnableToWriteFile, "UnableToWriteFile should not be empty")
	assert.NotEmpty(t, errors.UnAuth, "UnAuth should not be empty")
	assert.NotEmpty(t, errors.UnsupportedMediaType, "UnsupportedMediaType should not be empty")
	assert.NotEmpty(t, errors.UserResetFailed, "UserResetFailed should not be empty")
	assert.NotEmpty(t, errors.UserUpdateFailed, "UserUpdateFailed should not be empty")
	assert.NotEmpty(t, errors.UserNotFound, "UserNotFound should not be empty")
	assert.NotEmpty(t, errors.UserNotAdmin, "UserNotAdmin should not be empty")
	assert.NotEmpty(t, errors.UserUnauthorized, "UserUnauthorized should not be empty")
	assert.NotEmpty(t, errors.ClientNotFound, "ClientNotFound should not be empty")
	assert.NotEmpty(t, errors.ClientNotActive, "ClientNotActive should not be empty")
	assert.NotEmpty(t, errors.ClientNoAuth, "ClientNoAuth should not be empty")
	assert.NotEmpty(t, errors.ClientTokenGen, "ClientTokenGen should not be empty")
	assert.NotEmpty(t, errors.ClientNoEligibleTokens, "ClientNoEligibleTokens should not be empty")
	assert.NotEmpty(t, errors.IndexNoFile, "IndexNoFile should not be empty")
	assert.NotEmpty(t, errors.IndexNoAvail, "IndexNoAvail should not be empty")
	assert.NotEmpty(t, errors.IndexOutOfBounds, "IndexOutOfBounds should not be empty")
	assert.NotEmpty(t, errors.IndexTypeMismatch, "IndexTypeMismatch should not be empty")
	assert.NotEmpty(t, errors.InvalidAuth, "InvalidAuth should not be empty")
	assert.NotEmpty(t, errors.InvalidIndex, "InvalidIndex should not be empty")
	assert.NotEmpty(t, errors.InvalidIndexType, "InvalidIndexType should not be empty")
	assert.NotEmpty(t, errors.InvalidNodeId, "InvalidNodeId should not be empty")
	assert.NotEmpty(t, errors.InvalidUrlPassed, "InvalidUrlPassed should not be empty")
	assert.NotEmpty(t, errors.MongoDocNotFound, "MongoDocNotFound should not be empty")
	assert.NotEmpty(t, errors.NoAuth, "NoAuth should not be empty")
	assert.NotEmpty(t, errors.NodeReferenced, "NodeReferenced should not be empty")
	assert.NotEmpty(t, errors.UnAuth, "UnAuth should not be empty")
}

// TestErrorMessages tests that error messages are properly formatted
func TestErrorMessages(t *testing.T) {
	// Test a few error messages to ensure they are properly formatted
	assert.Contains(t, errors.InvalidAuth, "Invalid Auth Header", "InvalidAuth should contain 'Invalid Auth Header'")
	assert.Contains(t, errors.NodeNotFound, "Node not found", "NodeNotFound should contain 'Node not found'")
	assert.Contains(t, errors.NoAuth, "No Authorization", "NoAuth should contain 'No Authorization'")
	assert.Contains(t, errors.UnAuth, "User Unauthorized", "UnAuth should contain 'User Unauthorized'")
}
