openapi: 3.0.0
servers:
  - url: shock.mg-rast.org
info:
  description: |
  version: 1.0.0
  title: Shock2 API specification
  termsOfService: ''
tags:
  - name: node
    description: Node resource
  - name: node_acl
    description: Node ACL subresource
  - name: node_index
    description: Node index subresource
components:
  schemas:
    Node:
      properties:
        id:
          type: string
        file:
          type: string
        attributes:
          type: object
        indexes:
          type: string
        version:
          type: string
    # Both properties are required
      required:  
       - id
paths:
  '/node/{nodeId}':
    get:
      #description: 'get node'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Node'
      tags:
        - node
    parameters:
      - in: path
        name: nodeId
        schema:
          type: string
        required: true
      - in: query
        name: download
        schema:
          type: string
        required: false
        description: download file
    put:
      summary: ''
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
      tags:
        - node
    delete:
      summary: delete node
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
      tags:
        - node
  '/node':
    get:
      description: list nodes
      responses:
        '200':
          description: OK
      tags:
        - node
    parameters:
      - in: query
        name: query
        schema:
          type: string
        required: false
        description: search
      - in: query
        name: limit
        schema:
          type: integer
        required: false
      - in: query
        name: offset
        schema:
          type: integer
        required: false
  '/node/{nodeId}/acl':
    parameters:
      - in: path
        name: nodeId
        schema:
          type: string
        required: true
    get:
      summary: view node acls of type
      description: ''
      operationId: ''
      
      responses:
        default:
          description: Default error sample response
      tags:
        - node_acl
    put:
      summary: 'modify node acls of type '
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
      tags:
        - node_acl
  '/node/{nodeId}/acl/{type}':
    parameters:
      - in: path
        name: nodeId
        schema:
          type: string
        required: true
      - in: path
        name: type
        schema:
          type: string
        required: true
    get:
      summary: view node acls of type
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
      tags:
        - node_acl
    put:
      summary: 'modify node acls of type '
      description: ''
      operationId: ''
      parameters:
        - in: path
          name: nodeId
          schema:
            type: string
          required: true
      responses:
        default:
          description: Default error sample response
      tags:
        - node_acl
  '/node/{nodeId}/index/{type}':
    parameters:
      - in: path
        name: nodeId
        schema:
          type: string
        required: true
      - in: path
        name: type
        description: upload node index
        schema:
          type: string
        required: true    
    put:
      summary: create node indexes
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
      
      tags:
        - node_index
    delete:
      summary: delete node index
      description: ''
      parameters:
        - in: query
          name: users
          description: delete 
          schema:
            type: string
          required: false
      operationId: ''
      responses:
        default:
          description: Default error sample response
      tags:
        - nodeIndex
security: []
