openapi: 3.0.0
servers:
  - url: shock.mg-rast.org
info:
  description: |
  version: 1.0.0
  title: Shock2 API specification
  termsOfService: ''
tags:
  - name: node
    description: Node resource
  - name: node_acl
    description: Node ACL subresource
  - name: node_index
    description: Node index subresource
components:
 schemas:
   Node:
     properties:
       id:
         type: string
         description: unique identifier
       file:
         type: object
         description:  name, size, checksum(s).
       attributes:
         type: object
         description: arbitrary json. Queriable.
       indexes:
         type: string
         description: A set of indexes to use
       version:
         type: string
         description: a version stamp for this node
   # Both properties are required
     required:  
      - id
paths:
  '/node/{nodeId}':
    get:
      summary: view and download node
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Node'
              example:
                attributes: 
                created_on: '2014-06-16T11:08:17.955-05:00'
                file:
                  checksum: {}
                  format: ''
                  name: ''
                  size: 0
                  virtual: false
                  virtual_parts: []
                id: 130cadb5-9435-4bd9-be13-715ec40b2bb5
                indexes:
                  size:
                    total_units: 100
                    average_unit_size: 1048576
                last_modified: '2014-06-16T11:25:16.535-05:00'
                linkages: []
                tags: []
                type: basic
                version: aabfee3e4291a649c00984451e1ff891
      tags:
        - node
    parameters:
      - in: path
        name: nodeId
        schema:
          type: string
        required: true
      - in: query
        name: download
        schema:
          type: string
        required: false
        description: download file
    put:
      summary: 'update node'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
      tags:
        - node
    delete:
      summary: delete node
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
      tags:
        - node
  '/node':
    get:
      summary: list nodes
      parameters:
      - in: query
        name: query
        schema:
          type: boolean
          example: true
        required: false
      - in: query
        name: limit
        schema:
          type: integer
        required: false
      - in: query
        name: offset
        schema:
          type: integer
        required: false
      responses:
        '200':
          description: OK
      tags:
        - node
    post:
      summary: upload file
      parameters:
      - in: query
        name: attributes
        description: "specifies a file containing attributes in JSON format"
        schema:
          type: string
        required: false
        example: "attributes.json"
      - in: query
        name: attributes_str
        description: "attributes in JSON format"
        schema:
          type: string
          example: '{"project" : "human gut", "sample": "sample1"}'
        required: false
      responses:
        '200':
          description: OK
      tags:
        - node
    
  '/node/{nodeId}/acl':
    parameters:
      - in: path
        name: nodeId
        schema:
          type: string
        required: true
    get:
      summary: view node acls of type
      description: ''
      operationId: ''
      
      responses:
        default:
          description: Default error sample response
      tags:
        - node_acl
    put:
      summary: 'modify node acls of type '
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
      tags:
        - node_acl
  '/node/{nodeId}/acl/{type}':
    parameters:
      - in: path
        name: nodeId
        schema:
          type: string
        required: true
      - in: path
        name: type
        schema:
          type: string
        required: true
    get:
      summary: view node acls of type
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
      tags:
        - node_acl
    put:
      summary: 'modify node acls of type '
      description: ''
      operationId: ''
      parameters:
        - in: path
          name: nodeId
          schema:
            type: string
          required: true
      responses:
        default:
          description: Default error sample response
      tags:
        - node_acl
  '/node/{nodeId}/index/{type}':
    parameters:
      - in: path
        name: nodeId
        schema:
          type: string
        required: true
      - in: path
        name: type
        description: upload node index
        schema:
          type: string
        required: true    
    put:
      summary: create node indexes
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
      
      tags:
        - node_index
    delete:
      summary: delete node index
      description: ''
      parameters:
        - in: query
          name: users
          description: delete 
          schema:
            type: string
          required: false
      operationId: ''
      responses:
        default:
          description: Default error sample response
      tags:
        - node_index
security: []
