package fastq_test

import (
	. "github.com/MG-RAST/Shock/shock-server/node/file/format/astq"
	"testing"
)

func TestRegex(t *testing.T) {
	println("valid:")
	for _, s := range valid {
		println(Regex.MatchString(s))
	}
	println("invalid:")
	for _, s := range invalid {
		println(Regex.MatchString(s))
	}

}

var valid = []string{`@SEQ_ID
GATTTGGGGTTCAAAGCAGTATCGATCAAATAGTAAATCCATTTGTTCAACTCACAGTTT
+
!''*((((***+))%%%++)(%%%%).1***-+*''))**55CCF>>>>>>CCCCCCC65
@SEQ_ID
GATTTGGGGTTCAAAGCAGTATCGATCAAATAGTAAATCCATTTGTTCAACTCACAGTTT
+
!''*((((***+))%%%++)(%%%%).1***-+*''))**55CCF>>>>>>CCCCCCC65`, `@SEQ_ID
GATTTGGGGTTCAAAGCAGTATCGATCAAATAGTAAATCCATTTGTTCAACTCACAGTTT
+junkhhere
!''*((((***+))%%%++)(%%%%).1***-+*''))**55CCF>>>>>>CCCCCCC65
@SEQ_ID
GATTTGGGGTTCAAAGCAGTATCGATCAAATAGTAAATCCATTTGTTCAACTCACAGTTT
+junkhhere
!''*((((***+))%%%++)(%%%%).1***-+*''))**55CCF>>>>>>CCCCCCC65`}

var invalid = []string{`>S1
TGAATGTATTCCAGTAAACCGCCCGCGCAAGTAGGCTTCAAATGCCTGCACATTGTCCGT
GCCGCGTTTTCAAAGTTTCTGTTCTTCGCCCGAAAGAATAGGAAGAATTGATTTGGCGAC
CTGTTCGGAAACAATATCTTCAAGCGTCAAAACGTCGCTGAATTTTCATCAAAGGTCTTC
GCCCAACACGTCGAATTATCCTTGACGCTCAAAAGCTGCGCTGAAATGCGAATTCTATCA
CCGACGCGGCGGAGATTACCGTCAAGAATAAAATCAACGCCGAGTTCG
>S2
TTTCGAGCTCCCGAACATTGCCCGGCCAATGGTAGCGGCGCAAGAAGTCGAGGGCTTCCC
TGCTGAGCCGCGGTGGTTGCAGACGCGTGGGCCGCGCGCGGCTTTGGCGATGAAGTGGGC
GGCGAGCGCTGCGATATCCGCTACGCGTTCGCGCAGTGGTGGCACCTGGATGTGAAGTAC
GGCGAGCCGATAGAACAGGTCCTCTCTGAAGGTTCCCTGTCGCACCATCGATAGTAAGTC
TCGATTGGTGGCCGCGATCACTCGAGTGTCGACCGAAAACGAGGTCTGACTTCCGACGCG
CTCGATGCGGTTATCCTGCAATGTGCGCAGCAACGCCACT
>S3
TTTTATAACCGCGAGGACCTCTGGCAGTTCCCGCGCCAGCCGGGCGGCGATGGGATTGCA
ACGATGGCTCCCTATTACATCATCATGCGGCTGCCCGGTGAGCCGCAAGCCGAGTTCTTT
CTCATGGTCCCGATGGCGCCGAGTCGCCGCGACAACATGATCGCCTGGCTCGCGGCCCGT
TGCGACGCTCCCGACTACGGCAGACTGGTCGTCTACGAATTCCCCAAGGAGAAGCTCGTC
TACGGGCCGTTCCAGATCGAGGCGCGGATCAATCAGAGTACCGAGATATCGCAACAAATC
ACGCTGTGGAACCAGATGGGCTCGCGCGTGATACGCGGCGCAAAACCTGCTTGTGATCCC
GATCGAGAATTCGATACTTTATGTCACACCGCTCTATTTGCGAGCGGAACACGGACACTT
GCCGGAGCTG`, `@SEQ_ID
GATTTGGGGTTCAAAGCAGTATCGATCAA
ATAGTAAATCCATTTGTTCAACTCACAGTTT
+
!''*((((***+))%%%++)(%%%%).1*
**-+*''))**55CCF>>>>>>CCCCCCC65`, `SEQ_ID
GATTTGGGGTTCAAAGCAGTATCGATCAAATAGTAAATCCATTTGTTCAACTCACAGTTT
+
!''*((((***+))%%%++)(%%%%).1***-+*''))**55CCF>>>>>>CCCCCCC65
SEQ_ID
GATTTGGGGTTCAAAGCAGTATCGATCAAATAGTAAATCCATTTGTTCAACTCACAGTTT
+
!''*((((***+))%%%++)(%%%%).1***-+*''))**55CCF>>>>>>CCCCCCC65`, `@

+

`}
